### ISSUE TITLE
Log in sometimes gives error

### ISSUE THREAD

**Issue by jasonaowen** [jasonaowen/recurse-community-portfolio#84]
When logging in from `https://portfolio.recurse.com`, users are prompted to authorize the application at RC, then the site gives a red error at `/login`.

**Comment by Chandu0009** [comment]
Amazing! I like to share it with all my friends and hope they will like this information. 
Regards
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training In Hyderabad</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Online Training</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training</a>
<a href="http://abtrainings.com/courses/power-bi-online-training/">Power Bi Training Online </a>

**Comment by jasonaowen** [comment]
This was caused by a mismatch between the URL users requested, the URL the application saw, and the URL the Recurse Center OAuth server expected to see. It was fixed as part of #89, which involved improving the functionality of the RC proxy and switching the application server, which allowed switching the OAuth redirect URI to point to `portfolio.recurse.com`. See #89 for more details.
